add explicit coercion where TypeSsript 5 became more strict
haskell/actions pull request #252
Opened 2023-05-13 02:33 UTC by ulysses4ever

fix #227

The fix is taken from
https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-beta/#forbidden-implicit-coercions-in-relational-operators

2023-05-13 22:55 UTC, andreasabel requested changes
Thanks for the PR!

Could you include the bump to TypeScript 5 in this PR so that CI can verify your change sufficies?

2023-05-14 01:30 UTC, ulysses4ever commented
@andreasabel done

2023-05-15 09:58 UTC, andreasabel approved these changes

2023-05-15 09:59 UTC, merged

2023-05-15 10:00 UTC, andreasabel commented
Thanks, @ulysses4ever !